module.exports = (sequelize, Sequelize) => {
  const Cards = sequelize.define("cards", {
    id: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
      primaryKey: true
    },
    Bank: {type: Sequelize.STRING},
    Date: {type: Sequelize.DATE},
    Product: {type: Sequelize.STRING},
    Logo: {type: Sequelize.STRING},
    Scheme: {type: Sequelize.STRING},
    Name: {type: Sequelize.STRING},
    Bureau_Status : {type: Sequelize.DATE},
    Courier_Status : {type: Sequelize.DATE},
    Bureau_Status_Timestamp : {type: Sequelize.DATE},
    Courier_Status_Timestamp : {type: Sequelize.DATE},
    Address1: {type: Sequelize.STRING},
    Address2: {type: Sequelize.STRING},
    Address3: {type: Sequelize.STRING},
    City: {type: Sequelize.STRING},
    State: {type: Sequelize.STRING},
    Pin: {type: Sequelize.STRING},
    Mobile: {type: Sequelize.STRING},
    Other_Contact: {type: Sequelize.STRING},
    Reference_No: {type: Sequelize.STRING},
    AWB_No: {type: Sequelize.STRING},
    RTO_Address1: {type: Sequelize.STRING},
    RTO_Address2: {type: Sequelize.STRING},
    RTO_Address3: {type: Sequelize.STRING},
    RTO_City: {type: Sequelize.STRING},
    RTO_State: {type: Sequelize.STRING},
    RTO_Pin: {type: Sequelize.STRING},
    Office_Address1: {type: Sequelize.STRING},
    Office_Address2: {type: Sequelize.STRING},
    Office_Address3: {type: Sequelize.STRING},
    Office_City: {type: Sequelize.STRING},
    Office_State: {type: Sequelize.STRING},
    Office_Pin: {type: Sequelize.STRING},
    PA_Flag: {type: Sequelize.STRING},
    NRWC_Flag: {type: Sequelize.STRING},
    Priority: {type: Sequelize.STRING},
    Third_Party: {type: Sequelize.STRING},
    Bureau_Code: {type: Sequelize.INTEGER},
    Courier_Code: {type: Sequelize.INTEGER},
    Form_Factor: {type: Sequelize.STRING},
    Comments: {type: Sequelize.STRING},
    Personalized_NonPersonalized: {type: Sequelize.STRING},
    Individual_Bulk_Break: {type: Sequelize.STRING},
    Sub_Customer: {type: Sequelize.STRING},
    Status: {type: Sequelize.INTEGER},
    If_PULL: {type: Sequelize.STRING},
    Field_1: {type: Sequelize.STRING},
    Field_2: {type: Sequelize.STRING},
    Field_3: {type: Sequelize.STRING},
    Field_4: {type: Sequelize.DATE},
    Field_5: {type: Sequelize.DATE},
    Field_6: {type: Sequelize.INTEGER},
    Field_7: {type: Sequelize.INTEGER},
    createdAt: {
      type: Sequelize.DATE,
      defaultValue: new Date(),
    },
    updatedAt: {
      type: Sequelize.DATE,
      defaultValue: new Date(),
    }
  });

  return Cards;
};
