module.exports = (sequelize, datatypes) => {
  const Cards = sequelize.define("cards", {
    id: {
      type: datatypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    Bank: { type: datatypes.STRING },
    Date: { type: datatypes.DATE },
    Product: { type: datatypes.STRING },
    Logo: { type: datatypes.STRING },
    Scheme: { type: datatypes.STRING },
    Name: { type: datatypes.STRING },
    Bureau_Status: { type: datatypes.INTEGER },
    Courier_Status: { type: datatypes.INTEGER },
    Bureau_Status_Timestamp: { type: datatypes.DATE },
    Courier_Status_Timestamp: { type: datatypes.DATE },
    Address1: { type: datatypes.STRING },
    Address2: { type: datatypes.STRING },
    Address3: { type: datatypes.STRING },
    City: { type: datatypes.STRING },
    State: { type: datatypes.STRING },
    Pin: { type: datatypes.STRING },
    Mobile: { type: datatypes.STRING },
    Other_Contact: { type: datatypes.STRING },
    Reference_No: { type: datatypes.STRING },
    AWB_No: { type: datatypes.STRING },
    RTO_Address1: { type: datatypes.STRING },
    RTO_Address2: { type: datatypes.STRING },
    RTO_Address3: { type: datatypes.STRING },
    RTO_City: { type: datatypes.STRING },
    RTO_State: { type: datatypes.STRING },
    RTO_Pin: { type: datatypes.STRING },
    Office_Address1: { type: datatypes.STRING },
    Office_Address2: { type: datatypes.STRING },
    Office_Address3: { type: datatypes.STRING },
    Office_City: { type: datatypes.STRING },
    Office_State: { type: datatypes.STRING },
    Office_Pin: { type: datatypes.STRING },
    PA_Flag: { type: datatypes.STRING },
    NRWC_Flag: { type: datatypes.STRING },
    Priority: { type: datatypes.STRING },
    Third_Party: { type: datatypes.STRING },
    Bureau_Code: { type: datatypes.INTEGER },
    Courier_Code: { type: datatypes.INTEGER },
    Form_Factor: { type: datatypes.STRING },
    Comments: { type: datatypes.STRING },
    Personalized_NonPersonalized: { type: datatypes.STRING },
    Individual_Bulk_Break: { type: datatypes.STRING },
    Sub_Customer: { type: datatypes.STRING },
    Status: { type: datatypes.INTEGER },
    If_PULL: { type: datatypes.STRING },
    Field_1: { type: datatypes.STRING },
    Field_2: { type: datatypes.STRING },
    Field_3: { type: datatypes.STRING },
    Field_4: { type: datatypes.DATE },
    Field_5: { type: datatypes.DATE },
    Field_6: { type: datatypes.INTEGER },
    Field_7: { type: datatypes.INTEGER },
    createdBy: {
      type: datatypes.INTEGER,
      references: {
        model: sequelize.models.users,
        key: "id",
      },
    },
    modifiedBy: {
      type: datatypes.INTEGER,
      references: {
        model: sequelize.models.users,
        key: "id",
      },
    },
    createdAt: {
      type: datatypes.DATE,
      defaultValue: new Date(),
    },
    updatedAt: {
      type: datatypes.DATE,
      defaultValue: new Date(),
    },
  });

  return Cards;
};
